spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_epam
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: ""
  cache:
    type: redis
    
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.sro: INFO
    org.springframework: INFO
    org.hibernate: WARN

management:
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      all: true

storage:
  init:
    file: classpath:init_data.json

jwt:
  blacklist:
    prefix: "blacklisted_token:"
  refresh:
    prefix: "user:refresh_tokens:"
    expiry: 7

internal:
  service:
    token: "eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInN1YiI6ImNsaWVudC5jbGllbnQiLCJpYXQiOjE3NTIzMzk3MTQsImV4cCI6MTc4Mzg3NTcxNCwianRpIjoiYWE4ZDEwODEtNjhkMy00OGMzLTg4N2EtM2Y0YjY0M2Q5Nzg1In0.1CF-fhhN5GoVDAIWmoTNYi8DBVa3PE_we0g-SULHvVwEphYT1zfF6KZmHoRDdppgER9uyZN-RwYC9V24J0W9ww"
