spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_epam
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: ""
  cache:
    type: redis
    
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
    listener:
      ack-mode: manual_immediate
      retry-interval: 5000

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

logging:
  level:
    com.sro: INFO
    org.springframework: INFO
    org.hibernate: WARN

management:
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      all: true

storage:
  init:
    file: classpath:init_data.json

jwt:
  blacklist:
    prefix: "blacklisted_token:"
  refresh:
    prefix: "user:refresh_tokens:"
    expiry: 7
