server:
  port: 8888
  error:
    include-message: always

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srestrep74/Java-Specialization-Modules
          search-paths: 
            - infrastructure/config-server/src/main/resources/config
            - infrastructure/config-server/src/main/resources/config/{application}
          default-label: auth